# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    # Check for files with names that would conflict on a case-insensitive filesystem
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: mixed-line-ending
    # Sorts entries in requirements.txt
    -   id: requirements-txt-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# sort and remove unused imports
-   repo: https://github.com/sqlalchemyorg/zimports/
    rev: v0.6.0
    hooks:
    -   id: zimports

# Replace with `zimports` as it can remove unused imports
#-   repo: https://github.com/pycqa/isort
#    rev: 5.12.0
#    hooks:
#      - id: isort
#        name: isort (python)
#        args: ["--profile", "black", "--filter-files"]
#      - id: isort
#        name: isort (cython)
#        args: ["--profile", "black", "--filter-files"]
#        types: [cython]

# detect unused pieces of code
-   repo: https://github.com/jendrikseipp/vulture
    rev: v2.7
    hooks:
    -   id: vulture
        # tele_bot is excluded since there is no actual use of its methods
        args: ["--exclude", "venv,mail_saved,mail_test,m_saved,tele_bot", "./"]

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.11
